activitydb/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from decimal import Decimal
from datetime import datetime
import uuid
from django.utils.timezone import utc

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from simple_history.models import HistoricalRecords

# New user created generate a token
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class TolaSites(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255)
    agency_name = models.CharField(blank=True, null=True, max_length=255)
    agency_url = models.CharField(blank=True, null=True, max_length=255)
    tola_tables_url = models.CharField(blank=True, null=True, max_length=255)
    tola_tables_user = models.CharField(blank=True, null=True, max_length=255)
    tola_tables_token = models.CharField(blank=True, null=True, max_length=255)
    site = models.ForeignKey(Site)
    privacy_disclaimer = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now=False, blank=True, null=True)
    updated = models.DateTimeField(auto_now=False, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Tola Sites"

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        ''' On save, update timestamps as appropriate '''
        if kwargs.pop('new_entry', True):
            self.created = datetime.now()
        else:
            self.updated = datetime.now()
        return super(TolaSites, self).save(*args, **kwargs)


class TolaSitesAdmin(admin.ModelAdmin):
    list_display = ('name', 'agency_name')
    display = 'Tola Site'
    list_filter = ('name',)
    search_fields = ('name','agency_name')


class Country(models.Model):
    country = models.CharField("Country Name", max_length=255, blank=True)
    code = models.CharField("2 Letter Country Code", max_length=4, blank=True)
    description = models.TextField("Description/Notes", max_length=765,blank=True)
    latitude = models.CharField("Latitude", max_length=255, null=True, blank=True)
    longitude = models.CharField("Longitude", max_length=255, null=True, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('country',)
        verbose_name_plural = "Countries"
        app_label = 'activitydb'

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(Country, self).save()

    # displayed in admin templates
    def __unicode__(self):
        return self.country


class CountryAdmin(admin.ModelAdmin):
    list_display = ('name', 'create_date', 'edit_date')
    display = 'Country'


TITLE_CHOICES = (
    ('mr', 'Mr.'),
    ('mrs', 'Mrs.'),
    ('ms', 'Ms.'),
)


class TolaUser(models.Model):
    title = models.CharField(blank=True, null=True, max_length=3, choices=TITLE_CHOICES)
    name = models.CharField("Given Name", blank=True, null=True, max_length=100)
    employee_number = models.IntegerField("Employee Number", blank=True, null=True)
    user = models.OneToOneField(User, unique=True, related_name='tola_user')
    country = models.ForeignKey(Country, blank=True, null=True)
    countries = models.ManyToManyField(Country, verbose_name="Accessible Countries", related_name='countries', blank=True)
    tables_api_token = models.CharField(blank=True, null=True, max_length=255)
    privacy_disclaimer_accepted = models.BooleanField(default=False)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    @property
    def countries_list(self):
        return ', '.join([x.code for x in self.countries.all()])

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(TolaUser, self).save()


class TolaUserAdmin(admin.ModelAdmin):
    list_display = ('name', 'country')
    display = 'Tola User'
    list_filter = ('country',)
    search_fields = ('name','country__country','title')


class Sector(models.Model):
    sector = models.CharField("Sector Name", max_length=255, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('sector',)

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(Sector, self).save()

    # displayed in admin templates
    def __unicode__(self):
        return self.sector


class SectorAdmin(admin.ModelAdmin):
    list_display = ('sector', 'create_date', 'edit_date')
    display = 'Sector'


class Contact(models.Model):
    name = models.CharField("Name", max_length=255, blank=True, null=True)
    title = models.CharField("Title", max_length=255, blank=True, null=True)
    city = models.CharField("City/Town", max_length=255, blank=True, null=True)
    address = models.TextField("Address", max_length=255, blank=True, null=True)
    email = models.CharField("Email", max_length=255, blank=True, null=True)
    phone = models.CharField("Phone", max_length=255, blank=True, null=True)
    country = models.ForeignKey(Country)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('country','name','title')
        verbose_name_plural = "Contact"

    # onsave add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(Contact, self).save()

    # displayed in admin templates
    def __unicode__(self):
        return self.title + " " + self.name


class ContactAdmin(admin.ModelAdmin):
    list_display = ('name', 'country', 'create_date', 'edit_date')
    display = 'Contact'
    list_filter = ('create_date','country')
    search_fields = ('name','country','title','city')


# For programs that have custom dashboards. The default dashboard for all other programs is 'Program Dashboard'
class CustomDashboard(models.Model):
    dashboard_name = models.CharField("Custom Dashboard Name", max_length=255, blank=True)
    dashboard_description = models.TextField("Brief Description", null=True, blank=True, help_text="What does this custom dashboard display to the user?")
    is_public = models.BooleanField("External Public Dashboard", default=False)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('dashboard_name',)

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(CustomDashboard, self).save()

    # displayed in admin templates
    def __unicode__(self):
        return self.dashboard_name


class CustomDashboardAdmin(admin.ModelAdmin):
    list_display = ('dashboard_name', 'dashboard_description', 'create_date', 'edit_date')
    display = 'Custom Dashboard'


# For programs that have custom dashboards. The default dashboard for all other programs is 'Program Dashboard'
class FundCode(models.Model):
    name = models.CharField("Fund Code", max_length=255, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('name',)

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(FundCode, self).save()

    # displayed in admin templates
    def __unicode__(self):
        return self.name


class FundCodeAdmin(admin.ModelAdmin):
    list_display = ('name','program__name', 'create_date', 'edit_date')
    display = 'Fund Code'


class Program(models.Model):
    gaitid = models.CharField("ID", max_length=255, blank=True, unique=True)
    name = models.CharField("Program Name", max_length=255, blank=True)
    funding_status = models.CharField("Funding Status", max_length=255, blank=True)
    cost_center = models.CharField("Fund Code", max_length=255, blank=True, null=True)
    fund_code = models.ManyToManyField(FundCode, blank=True)
    description = models.TextField("Program Description", max_length=765, null=True, blank=True)
    sector = models.ManyToManyField(Sector, blank=True)
    dashboard_name = models.ForeignKey(CustomDashboard, null=True, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)
    budget_check = models.BooleanField("Enable Approval Authority Matrix", default=False)
    country = models.ManyToManyField(Country)
    user_access = models.ManyToManyField(TolaUser, blank=True)

    class Meta:
        ordering = ('name',)

    # on save add create date or update edit date
    def save(self, *args, **kwargs):
        if not 'force_insert' in kwargs:

templates/indicators/collecteddata_form.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li><a href="/indicators/collecteddata/0/0/"> Data</a></li>
  <li class="active">Output Form</li>
</ol>

{% endblock %}
{% block page_title %}Collected Indicator Data{% endblock %}

{% block content %}
    <span style="float: right;"><a onclick="newPopup('https://docs.google.com/document/d/1sTBwo-oueQeH9NTGDXpbYZdlBTpRXBBK14IZUS0wN08/','Form Help/Guidance'); return false;" href="#" class="btn btn-sm btn-info">Form Help/Guidance</a></span>
    {% include "form_guidance.html" %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/select2.min.js"></script>
    <link href="{{ STATIC_URL }}css/select2.min.css" rel="stylesheet" />
    <script type="text/javascript">
        //Searchable select option for service indicator
        $(document).ready(function() {
            /* add select2 js library to the indicator select box */
            $("#id_site").select2();
            $("#id_tola_table").select2();
            $("#id_evidence").select2();
            $("#id_agreement").select2();
        });

    </script>

    {% if form.errors %}
        <div class="help-block">
        {% for field in form %}
            {% for error in field.errors %}
                    <strong><i>{{ field.label }}</i> - {{ error|escape }}</strong>&nbsp;
            {% endfor %}
        {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
	{% csrf_token %}
    {% load crispy_forms_tags %}
    {% crispy form %}

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div> <!-- /.modal-content -->
        </div> <!-- /.modal-dialog -->
    </div> <!-- /.modal -->

{% endblock content %}

templates/indicators/indicator_form.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li class="active">Indicator Form</li>
</ol>
{% endblock %}
{% block page_title %}Indicator{% endblock %}

{% block content %}
    {% include "form_guidance.html" %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/select2.min.js"></script>
    <link href="{{ STATIC_URL }}css/select2.min.css" rel="stylesheet" />
    <script type="text/javascript">
        //Searchable select option for service indicator
        $(document).ready(function() {
            /* add select2 js library to the indicator select box */
            $("#id_program").select2();
            $("#id_strategic_objectives").select2();
        });

    </script>

    {% if form.errors %}
        <div class="help-block">
        {% for field in form %}
            {% for error in field.errors %}
                    <strong><i>{{ field.label }}</i> - {{ error|escape }}</strong>&nbsp;
            {% endfor %}
        {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
	{% csrf_token %}
    {% load crispy_forms_tags %}
    {% crispy form %}

{% endblock content %}